# Generated by Django 4.2.3 on 2023-09-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registation',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
